/*
1. CREEZ UN CHAMPS TEXTE DANS LA PAGE HTML (COURS HTML)
1.CREEZ UN CHAMPS  BOUTON DANS LA PAGE HTML
2.AJOUTEZ DANS LE CHAMPS BOUTON UN EVENEMENT QUI VA SE DECLENCHER AU CLIQUE
3.L EVENEMENT VA DECLENCHER UNE FONCTIONQUI VA FAIRE LA CHOSE SUIVANTE :
5.AFFICHE DANS UNE DIV CE QU'ON A ECRIS DEPUIS LE CHAMPS TEXTE
6.RECUPERER LA VALEUR ECRIS DANS LE TEXTE DE LE TRANSFORMER EN NUMERIQUE
7.DE LE COMPARER A UN NOMBRE ALEATOIRE QUI SERAIT STOCKE DANS UNE VARIABLE
8 . SI ON EST = ON ECRIS DANS LA DIV GAGNE LE JEU
9 . SI ON EST > ON ECRIS DANS LA DIV CEST MOINS 
10 . SI ON EST < ON ECRIS DANS LA DIV CEST PLUS */
function barbie(){
    console.log("Bonjour ! ")

    //var_texte=document.getElementById("name").value;

   // console.log(var_texte)

   // document.getElementById("madiv").innerHTML=var_texte

    document.getElementById("madiv").innerHTML=document.getElementById("name").value;

    document.getElementById("bouton_text").innerHTML=document.getElementById("name").value;

}



